version: "3"
services:
  rinha:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_DATABASE=rinha
      - POSTGRESQL_PASSWORD=rinha123
